### ISSUE TITLE
Setting birthdate actually sets it one day too early

### ISSUE THREAD

**Issue by lucleray** [hellocomet/tech-support#2]
# 🐞 Bug report 🐛

## Steps to reproduce

I'm setting my birthdate to my actual birthdate : 19/11. It saves, but when I refresh the page, it shows 18/11.

I'm in a different timezone (kuala lumpur, myt), so it's also probably related to that 🙂

## Behavior

I set my birthdate to 19/11. It saves automatically. I refresh the page.

 ☀️ What was expected : my birthdate is **19/11** when I refresh the page

☁️ What actually happened : my birthdate is **18/11** when I refresh the page 

## Suggestions

Store the date without the timezone in the database ? 🤔

**Comment by bokub** [comment]
Same problem, but my timezone is Europe/Paris, so I guess the bug is not related to the timezone.

Additional info: the date-picker shows the right date when opened, which is quite weird

**Comment by Dam-Buty** [comment]
Hi @lucleray & @bokub , thanks for this bug report :)

This issue has been added to our internal backlog. For future reference, it is logged as issue #1188 .

Cheers (and happy new year to you both 🎉 🍾)
Dams
